<?php

$title = 'Shopping Cart';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Price</th>       
        <th>Photo</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($products as $product) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($product['name']); ?></td>
            <td><?php echo $this->escapeHtml($product['price']) . ' руб.';?></td>
            <td>
                <img height="50" src="<?php echo $this->basePath('photo/') . $product['photo']; ?> " />
            </td>
            <td>
                <a href="<?php echo $this->url('shoppingCart', array('action' => 'delete', 'id' => $product['id']));
    ?>">Delete</a> |
                <a href="#" onclick="mainPage.shoppingCart.update('<?php echo $product['id']; ?>'); return false;">Update</a>
                <input class="product-count" type="number" name="product_count" id="productCount_<?php echo $product['id']; ?>" min="1" max="10" value="<?php echo $product['product_count'];?>">
            </td>
        </tr>
    <?php endforeach; ?>
</table>